package TestQuestion1GUI;

//Enter your examination number here.

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Question1GUI extends javax.swing.JFrame {

   Question1_DBGUI DB = new Question1_DBGUI();
   String sql = ""; 
    
    public Question1GUI() {
        initComponents();
        JOptionPane.showMessageDialog(null, DB.getMessage());    
    }
    
   /** This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaQ1 = new javax.swing.JTextArea();
        mnuMainQ1 = new javax.swing.JMenuBar();
        mnuOptionA = new javax.swing.JMenu();
        mnuOptionB = new javax.swing.JMenu();
        mnuOptionC = new javax.swing.JMenu();
        mnuOptionD = new javax.swing.JMenu();
        mnuOptionE = new javax.swing.JMenu();
        mnuOptionF = new javax.swing.JMenu();
        mnuOptionG = new javax.swing.JMenu();
        mnuQuit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Question 1 - GUI - ");

        txaQ1.setColumns(20);
        txaQ1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txaQ1.setRows(5);
        jScrollPane1.setViewportView(txaQ1);

        mnuOptionA.setText("Option A");
        mnuOptionA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuOptionAMouseClicked(evt);
            }
        });
        mnuMainQ1.add(mnuOptionA);

        mnuOptionB.setText("Option B");
        mnuOptionB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuOptionBMouseClicked(evt);
            }
        });
        mnuMainQ1.add(mnuOptionB);

        mnuOptionC.setText("Option C");
        mnuOptionC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuOptionCMouseClicked(evt);
            }
        });
        mnuMainQ1.add(mnuOptionC);

        mnuOptionD.setText("Option D");
        mnuOptionD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuOptionDMouseClicked(evt);
            }
        });
        mnuMainQ1.add(mnuOptionD);

        mnuOptionE.setText("Option E");
        mnuOptionE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuOptionEMouseClicked(evt);
            }
        });
        mnuMainQ1.add(mnuOptionE);

        mnuOptionF.setText("Option F");
        mnuOptionF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuOptionFMouseClicked(evt);
            }
        });
        mnuMainQ1.add(mnuOptionF);

        mnuOptionG.setText("Option G");
        mnuOptionG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuOptionGMouseClicked(evt);
            }
        });
        mnuMainQ1.add(mnuOptionG);

        mnuQuit.setText("Quit");
        mnuQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuQuitMouseClicked(evt);
            }
        });
        mnuMainQ1.add(mnuQuit);

        setJMenuBar(mnuMainQ1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-487)/2, (screenSize.height-334)/2, 487, 334);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuQuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuQuitMouseClicked
        try {
            DB.disconnect();
        } catch (SQLException ex) {
            Logger.getLogger(Question1GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_mnuQuitMouseClicked

    private void mnuOptionAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuOptionAMouseClicked
        // TODO add your handling code here:
        
        sql = "";        
        
        try {
            DB.query(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Question1GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        txaQ1.setText(DB.getMessage());
    }//GEN-LAST:event_mnuOptionAMouseClicked

    private void mnuOptionBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuOptionBMouseClicked
        // TODO add your handling code here:
                
        sql = "";
        
        
        try {
            DB.query(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Question1GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        txaQ1.setText(DB.getMessage());       
    }//GEN-LAST:event_mnuOptionBMouseClicked

    private void mnuOptionCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuOptionCMouseClicked
        // TODO add your handling code here:
        String sX = JOptionPane.showInputDialog("Question 1:");
        
        sql = "";
        
        try {
            DB.query(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Question1GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        txaQ1.setText(DB.getMessage());        
    }//GEN-LAST:event_mnuOptionCMouseClicked

    private void mnuOptionDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuOptionDMouseClicked
        // TODO add your handling code here:
        
        sql = "";
        
        try {
            DB.query(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Question1GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        txaQ1.setText(DB.getMessage());        
    }//GEN-LAST:event_mnuOptionDMouseClicked

    private void mnuOptionEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuOptionEMouseClicked
        // TODO add your handling code here:
        
        sql = "";
        
        
        try {
            DB.query(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Question1GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        txaQ1.setText(DB.getMessage());        
    }//GEN-LAST:event_mnuOptionEMouseClicked

    private void mnuOptionFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuOptionFMouseClicked
        // TODO add your handling code here:
        
        sql = "";
        
        
        try {
            DB.query(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Question1GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        txaQ1.setText(DB.getMessage());        
    }//GEN-LAST:event_mnuOptionFMouseClicked

    private void mnuOptionGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuOptionGMouseClicked
        // TODO add your handling code here:
        
        sql = "";
        
        
        try {
            DB.query(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Question1GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        txaQ1.setText(DB.getMessage());        
    }//GEN-LAST:event_mnuOptionGMouseClicked

    public static void main(String args[]) {
        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Question1GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar mnuMainQ1;
    private javax.swing.JMenu mnuOptionA;
    private javax.swing.JMenu mnuOptionB;
    private javax.swing.JMenu mnuOptionC;
    private javax.swing.JMenu mnuOptionD;
    private javax.swing.JMenu mnuOptionE;
    private javax.swing.JMenu mnuOptionF;
    private javax.swing.JMenu mnuOptionG;
    private javax.swing.JMenu mnuQuit;
    private javax.swing.JTextArea txaQ1;
    // End of variables declaration//GEN-END:variables
}
