/*
 * Type your  examnumber here
 */
package Question3Package;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Question3 extends javax.swing.JFrame {

    int[] arrGirls = new int[8];
    int[] arrBoys = new int[8];
    String[] arrSchoolNames = {"Bedworthpark High School", "Bristol House", "Broadlands Technical High", "Griffiths House", "Fenham College", "Edenburgh High School", "Rethanda College", "Sheffield High School"};
    String[] arrSchoolAbrv = {"BPK", "BSL", "BRT", "GFH", "FNH", "EDB", "RTN", "SFD"};
    int[][] arrSchoolResults = {{365, 458, 214, 0}, {255, 125, 128, 0}, {489, 499, 478, 0}, {211, 212, 256, 0}, {356, 345, 387, 0}, {479, 508, 479, 0}, {259, 245, 287, 0}, {302, 315, 354, 0}};

    public void fillComboBox() {
        for (int tel = 0; tel < 8; tel++) {
            cbxSchool.addItem("" + arrSchoolAbrv[tel]);
        }
    }

    public Question3() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setVisible(true);
        fillComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnQ3_2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cbxSchool = new javax.swing.JComboBox();
        btnQ3_1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnQ3_3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PC Athletics Championships ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 51, 255))); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Question 3.2"));

        btnQ3_2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQ3_2.setText("Average Results");
        btnQ3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ3_2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnQ3_2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQ3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Question 3.1"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Select School"));

        btnQ3_1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQ3_1.setText("Display Report");
        btnQ3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ3_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQ3_1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(cbxSchool, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(cbxSchool, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQ3_1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Question 3.3"));

        btnQ3_3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQ3_3.setText("Swap Points");
        btnQ3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ3_3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQ3_3, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQ3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 143, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(null);

        txaOutput.setColumns(20);
        txaOutput.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txaOutput.setRows(5);
        txaOutput.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "School Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), java.awt.Color.blue)); // NOI18N
        jScrollPane1.setViewportView(txaOutput);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 658, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQ3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ3_1ActionPerformed
        String schoolCode = cbxSchool.getSelectedItem().toString();
        int counter = 0;
        for (int i = 0; i < arrSchoolAbrv.length; i++) {
            if (schoolCode.equals(arrSchoolAbrv[i])) {
                counter = i;
            }
        }
        String schoolName = arrSchoolNames[counter];
        String[] retrievedData = this.retrieveFileData();
        ArrayList<String> schoolData = new ArrayList<String>();
        for (String data : retrievedData) {
            String[] contents = data.split("#");
            String[] containedData = contents[0].split(";");
            String schoolAbbreviation = containedData[1];
            if (schoolAbbreviation.equals(schoolCode)) {
                schoolData.add(data);
            }
        }
        String[] schoolInfo = schoolData.toArray(new String[schoolData.size()]);
        int[][] schoolResults = new int[8][4];

        // Initializing Array to Zero
        for (int i = 0; i < schoolResults.length; i++) {
            for (int j = 0; j < 4; j++) {
                schoolResults[i][j] = 0;
            }
        }

        for (int i = 0; i < schoolResults.length; i++) {
            schoolResults[i][0] = i + 1;

            for (String data : schoolInfo) {
                String[] contents = data.split("#");
                String[] infoP1 = contents[0].split(";");
                String entryID = infoP1[0];
                String schoolAbv = infoP1[1];
                String[] infoP2 = contents[1].split(";");
                int place = Integer.parseInt(infoP2[1]);
                String[] participantData = infoP2[0].split("-");
                String event = participantData[0];
                String[] details = participantData[1].split(" ");
                String gender = details[0];
                String ageGroup = details[1];

                if (place == (i + 1)) {
                    switch (gender) {
                        case "Boys":
                            schoolResults[i][1]++;
                            break;
                        case "Girls":
                            schoolResults[i][2]++;
                    }
                    schoolResults[i][3]++;
                }
            }

        }

        String output = String.format("School: %s (%s)\n\n"
                + "%-15s%-15s%-15s%-15s\n", schoolName, schoolCode, "Place", "Boys", "Girls", "Total");
        for (int i = 0; i < schoolResults.length; i++) {
            int resultPlace = schoolResults[i][0];
            int boysResults = schoolResults[i][1];
            int girlsResults = schoolResults[i][2];
            int totalResults = schoolResults[i][3];
            output += String.format("%-15d%-15d%-15d%-15d\n", resultPlace, boysResults, girlsResults, totalResults);
        }
        txaOutput.setText(output);
    }//GEN-LAST:event_btnQ3_1ActionPerformed

    private void btnQ3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ3_2ActionPerformed
        txaOutput.setText("Results of schools over the past three years : \n\n");
        String output = String.format("%-15s%-15s%-15s%-15s%-15s\n", "", "2012", "2013", "2014", "Average Points");

        // Done this calculation based method "on the fly" rather than creating a two-dimensional array and then reading from it
        /* It's normally much faster to do "on the fly" methods, it would be suitable to do in situations where 
         computing resources are minimal and where time is of the essence. */
        double highestAverage = 0.00;

        String[][] results = new String[arrSchoolAbrv.length][5];
        for (int i = 0; i < results.length; i++) {
            results[i][0] = arrSchoolAbrv[i];
            results[i][1] = arrSchoolResults[i][0] + "";
            results[i][2] = arrSchoolResults[i][1] + "";
            results[i][3] = arrSchoolResults[i][2] + "";
            double average = (arrSchoolResults[i][0] + arrSchoolResults[i][1] + arrSchoolResults[i][2]) / 3;
            results[i][4] = average + "";
            if (average > highestAverage) {
                highestAverage = average; // Updating Average
            }
        }

        // Determining schools that achieved the highest average points
        for (int i = 0; i < results.length; i++) {
            double schoolAverage = Double.parseDouble(results[i][4]);
            if (schoolAverage == highestAverage) {
                results[i][0] += "*";
            }
        }

        for (int i = 0; i < results.length; i++) {
            output += String.format("%-15s%-15s%-15s%-15s%-15s\n", results[i][0], results[i][1],
                    results[i][2], results[i][3], results[i][4]);
        }
        txaOutput.append(output);


    }//GEN-LAST:event_btnQ3_2ActionPerformed

    private void btnQ3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ3_3ActionPerformed
        int[] bpk = arrSchoolResults[0];
        int[] bsl = arrSchoolResults[1];
        arrSchoolResults[1] = bpk;
        arrSchoolResults[0] = bsl;
        btnQ3_2ActionPerformed(evt); 
    }//GEN-LAST:event_btnQ3_3ActionPerformed

    public String[] retrieveFileData() {
        String content = "";
        String[] textData = {};
        try {
            Scanner textFileScanner = new Scanner(new FileReader("Results.txt")).useDelimiter(",\\s*");
            while (textFileScanner.hasNext()) {
                content = textFileScanner.next();
            }
            textData = content.split("\r\n");
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        return textData;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Question3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Question3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Question3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Question3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Question3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQ3_1;
    private javax.swing.JButton btnQ3_2;
    private javax.swing.JButton btnQ3_3;
    private javax.swing.JComboBox cbxSchool;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaOutput;
    // End of variables declaration//GEN-END:variables
}
