package Question1Package;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author NSC2229
 */
public class Question1 extends javax.swing.JFrame {

    DecimalFormat df = new DecimalFormat("0.00");
    String activityType = "Quiz";
    int numParticipants = 50;

    /**
     * Creates new form Quiz
     */
    public Question1() {
        initComponents();
        this.setLocationRelativeTo(this);
        txfEvent.setText(activityType);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblCategory = new javax.swing.JLabel();
        lblEvent = new javax.swing.JLabel();
        txfEvent = new javax.swing.JTextField();
        btnQues1_1 = new javax.swing.JButton();
        cmbCategory = new javax.swing.JComboBox();
        lblOutput = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnQues1_2 = new javax.swing.JButton();
        txfIncome = new javax.swing.JTextField();
        lblNumParticipants = new javax.swing.JLabel();
        txfNumParticipants = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnQues1_3 = new javax.swing.JButton();
        txfAns_1_3 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaOutput_1_4 = new javax.swing.JTextArea();
        btnQues1_4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnQues1_6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaOutput_1_6 = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        rbtRound1 = new javax.swing.JRadioButton();
        rbtRound2 = new javax.swing.JRadioButton();
        chbBonus = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaOutput_1_5 = new javax.swing.JTextArea();
        btnQues1_5 = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Question 1.1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        lblCategory.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCategory.setText("Category");

        lblEvent.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEvent.setText("Event");

        txfEvent.setEditable(false);
        txfEvent.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txfEvent.setText(" ");

        btnQues1_1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnQues1_1.setText("Question 1.1");
        btnQues1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQues1_1ActionPerformed(evt);
            }
        });

        cmbCategory.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "General knowledge", "History", "Sport", "Science", "Mathematics" }));
        cmbCategory.setSelectedIndex(-1);

        lblOutput.setText("<Output label>");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnQues1_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEvent)
                            .addComponent(lblCategory))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCategory, 0, 267, Short.MAX_VALUE)
                            .addComponent(txfEvent))))
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEvent)
                    .addComponent(txfEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategory)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnQues1_1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(lblOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        lblOutput.getAccessibleContext().setAccessibleName("lblOutput");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Question 1.2"));

        btnQues1_2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnQues1_2.setText("Question 1.2");
        btnQues1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQues1_2ActionPerformed(evt);
            }
        });

        txfIncome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txfIncome.setText(" ");
        txfIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfIncomeActionPerformed(evt);
            }
        });

        lblNumParticipants.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNumParticipants.setText("Number of participants");

        txfNumParticipants.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumParticipants, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnQues1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfNumParticipants, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumParticipants, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfNumParticipants, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQues1_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfIncome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Question 1.3"));

        btnQues1_3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnQues1_3.setText("Question 1.3");
        btnQues1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQues1_3ActionPerformed(evt);
            }
        });

        txfAns_1_3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txfAns_1_3.setText(" ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQues1_3)
                .addGap(30, 30, 30)
                .addComponent(txfAns_1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQues1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfAns_1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Question 1.4"));

        txaOutput_1_4.setColumns(20);
        txaOutput_1_4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txaOutput_1_4.setRows(5);
        jScrollPane1.setViewportView(txaOutput_1_4);

        btnQues1_4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnQues1_4.setText("Question 1.4");
        btnQues1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQues1_4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(btnQues1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnQues1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Question 1.6"));

        btnQues1_6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnQues1_6.setText("Question 1.6");
        btnQues1_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQues1_6ActionPerformed(evt);
            }
        });

        txaOutput_1_6.setColumns(20);
        txaOutput_1_6.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txaOutput_1_6.setRows(5);
        jScrollPane2.setViewportView(txaOutput_1_6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addComponent(btnQues1_6)
                .addGap(116, 116, 116))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQues1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Question 1.5"));

        buttonGroup1.add(rbtRound1);
        rbtRound1.setText("Round 1");
        rbtRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtRound1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtRound2);
        rbtRound2.setText("Round 2");
        rbtRound2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtRound2ActionPerformed(evt);
            }
        });

        chbBonus.setText("Bonus questions");
        chbBonus.setEnabled(false);

        txaOutput_1_5.setColumns(20);
        txaOutput_1_5.setRows(5);
        jScrollPane3.setViewportView(txaOutput_1_5);

        btnQues1_5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnQues1_5.setText("Question 1.5");
        btnQues1_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQues1_5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtRound1)
                    .addComponent(rbtRound2)
                    .addComponent(chbBonus)
                    .addComponent(btnQues1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(rbtRound1)
                .addGap(18, 18, 18)
                .addComponent(rbtRound2)
                .addGap(29, 29, 29)
                .addComponent(chbBonus)
                .addGap(18, 18, 18)
                .addComponent(btnQues1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQues1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQues1_1ActionPerformed
        String event = txfEvent.getText();
        String category = cmbCategory.getSelectedItem().toString();
        lblOutput.setText(String.format("%s:%s", event, category));
    }//GEN-LAST:event_btnQues1_1ActionPerformed

    private void btnQues1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQues1_2ActionPerformed
        int numberParticipants = Integer.parseInt(txfNumParticipants.getText());
        this.numParticipants = numberParticipants;
        double total;
        if (numberParticipants > 20) {
            total = 20 * 25;
            numberParticipants -= 20;
            total += numberParticipants * 30; // Calculuting total for remainder
        } else {
            total = numberParticipants * 25;
        }
        txfIncome.setText(String.format("R %.2f", total));
    }//GEN-LAST:event_btnQues1_2ActionPerformed

    private void btnQues1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQues1_3ActionPerformed
        int base = Integer.parseInt(JOptionPane.showInputDialog(null, "Enter base:"));
        int exponent = Integer.parseInt(JOptionPane.showInputDialog(null, "Enter exponent:"));
        double x = Math.sqrt(Math.pow(base, exponent));
        txfAns_1_3.setText(String.format("x = %.2f", x));
    }//GEN-LAST:event_btnQues1_3ActionPerformed

    private void btnQues1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQues1_4ActionPerformed
        btnQues1_2ActionPerformed(evt);
        double slices = this.numParticipants * 3;
        double pizzas = slices / 8;
        int pizzasToOrder = (int) Math.round(pizzas);
        String output = String.format("Exact Value = %.4f\n"
                + "Number of Pizzas to Order = %d", pizzas, pizzasToOrder);
        txaOutput_1_4.setText(output);
    }//GEN-LAST:event_btnQues1_4ActionPerformed

    private void btnQues1_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQues1_6ActionPerformed
        int seats = 28;
        double ticketPrice = 52.00;
        double totalIncome = 0.00;
        DecimalFormat df = new DecimalFormat("R0.00");
        String output = String.format("%-10s%-10s%-15s%-10s\n\n", "Row", "Seats", "Ticket Price", "Income");
        for (int row = 1; row <= 20; row++) {
            seats += 2;
            ticketPrice -= 2.00;
            double income = seats*ticketPrice;
            totalIncome += income;
            output += String.format("%-10d%-10d%-15s%-10s\n", row, seats, df.format(ticketPrice), df.format(income)); 
        }
        output+= String.format("\n\nTotal Income: R%.2f", totalIncome);
        txaOutput_1_6.setText(output); 
    }//GEN-LAST:event_btnQues1_6ActionPerformed

    private void rbtRound2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtRound2ActionPerformed
        chbBonus.setEnabled(true);
    }//GEN-LAST:event_rbtRound2ActionPerformed

    private void rbtRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtRound1ActionPerformed
        chbBonus.setEnabled(false);
    }//GEN-LAST:event_rbtRound1ActionPerformed

    private void btnQues1_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQues1_5ActionPerformed
        int questions = 0;
        if (rbtRound1.isSelected() == true) {
            questions = 5;
        } else if (rbtRound2.isSelected() == true) {
            questions = 8;
            chbBonus.setEnabled(true);
            if (chbBonus.isSelected() == true) {
                questions += 2;
            }
        }



        // Code to determine the number of questions


        // Question 1.5.2 
        txaOutput_1_5.setText("");
        txaOutput_1_5.append("Questions to answer\n");
        String output = "";
        for (int i = 1; i <= questions; i++) {
            for (int j = questions; j >= i; j--) {
                output = output + (j + " ");
            }
            output = output + "\n";
        }
        txaOutput_1_5.append(output + "\nQuiz completed");

    }//GEN-LAST:event_btnQues1_5ActionPerformed

    private void txfIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfIncomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Question1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQues1_1;
    private javax.swing.JButton btnQues1_2;
    private javax.swing.JButton btnQues1_3;
    private javax.swing.JButton btnQues1_4;
    private javax.swing.JButton btnQues1_5;
    private javax.swing.JButton btnQues1_6;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chbBonus;
    private javax.swing.JComboBox cmbCategory;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblEvent;
    private javax.swing.JLabel lblNumParticipants;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JRadioButton rbtRound1;
    private javax.swing.JRadioButton rbtRound2;
    private javax.swing.JTextArea txaOutput_1_4;
    private javax.swing.JTextArea txaOutput_1_5;
    private javax.swing.JTextArea txaOutput_1_6;
    private javax.swing.JTextField txfAns_1_3;
    private javax.swing.JTextField txfEvent;
    private javax.swing.JTextField txfIncome;
    private javax.swing.JTextField txfNumParticipants;
    // End of variables declaration//GEN-END:variables
}
