package Question2Package;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.text.DecimalFormat;
import java.util.Scanner;
import javax.swing.JOptionPane;

public class Question2_Memo extends javax.swing.JFrame {

    HomeLoan loanObj;
    DecimalFormat df = new DecimalFormat("R 0.00");

    public Question2_Memo() {
        initComponents();
        this.setLocationRelativeTo(this);
        btnEvaluate.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        pnlPossibleApplicants = new javax.swing.JPanel();
        cmbApplicants = new javax.swing.JComboBox();
        btnLocateApplicant = new javax.swing.JButton();
        pnlApplicationStatus = new javax.swing.JPanel();
        btnEvaluate = new javax.swing.JButton();
        txfInterest = new javax.swing.JTextField();
        lblInterestRateH = new javax.swing.JLabel();
        cmbYears = new javax.swing.JComboBox();
        lblYearsH = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaOutput = new javax.swing.JTextArea();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Home loan applications", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        pnlPossibleApplicants.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Names of possible applicants", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        cmbApplicants.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbApplicants.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  "","Abdul Brouwer", "John Smith", "Xavier Outland", "Nobuko Hobgood", "Paula Redhat"}));
        cmbApplicants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbApplicantsActionPerformed(evt);
            }
        });

        btnLocateApplicant.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLocateApplicant.setText("Find applicant ");
        btnLocateApplicant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocateApplicantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPossibleApplicantsLayout = new javax.swing.GroupLayout(pnlPossibleApplicants);
        pnlPossibleApplicants.setLayout(pnlPossibleApplicantsLayout);
        pnlPossibleApplicantsLayout.setHorizontalGroup(
            pnlPossibleApplicantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPossibleApplicantsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPossibleApplicantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLocateApplicant, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbApplicants, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pnlPossibleApplicantsLayout.setVerticalGroup(
            pnlPossibleApplicantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPossibleApplicantsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbApplicants, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnLocateApplicant, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pnlApplicationStatus.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Evaluate application status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        btnEvaluate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEvaluate.setText("Evaluate application");
        btnEvaluate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluateActionPerformed(evt);
            }
        });

        txfInterest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txfInterest.setText("9.0");

        lblInterestRateH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInterestRateH.setText("Interest rate (%)");

        cmbYears.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbYears.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "20", "25", "30" }));

        lblYearsH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblYearsH.setText("Years");

        javax.swing.GroupLayout pnlApplicationStatusLayout = new javax.swing.GroupLayout(pnlApplicationStatus);
        pnlApplicationStatus.setLayout(pnlApplicationStatusLayout);
        pnlApplicationStatusLayout.setHorizontalGroup(
            pnlApplicationStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlApplicationStatusLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(pnlApplicationStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEvaluate, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlApplicationStatusLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(pnlApplicationStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbYears, 0, 75, Short.MAX_VALUE)
                            .addComponent(lblYearsH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlApplicationStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblInterestRateH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txfInterest))))
                .addGap(19, 19, 19))
        );
        pnlApplicationStatusLayout.setVerticalGroup(
            pnlApplicationStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlApplicationStatusLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(pnlApplicationStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYearsH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInterestRateH, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlApplicationStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbYears, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnEvaluate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPossibleApplicants, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlApplicationStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlApplicationStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPossibleApplicants, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        txaOutput.setColumns(20);
        txaOutput.setRows(5);
        jScrollPane1.setViewportView(txaOutput);

        btnClose.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnLocateApplicantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocateApplicantActionPerformed
        String applicant = (String) (cmbApplicants.getSelectedItem());
        if (applicant.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Select an applicant", "Warning", 0);
            txaOutput.setText("");
        } else {
            try {
                Scanner sc = new Scanner(new FileReader(applicant + ".txt"));
                txaOutput.setText("A home loan application was found for " + applicant);
                String name = sc.nextLine();
                double income = Double.parseDouble(sc.nextLine());
                double expenditure = Double.parseDouble(sc.nextLine());
                double loanAmount = Double.parseDouble(sc.nextLine());
                double disposableIncome = income - expenditure;
                loanObj = new HomeLoan(applicant, disposableIncome, loanAmount);
                JOptionPane.showMessageDialog(null, "Loan object successfully created");
                btnEvaluate.setEnabled(true);
            } catch (FileNotFoundException e) {
                txaOutput.setText("No home loan application was submitted by " + applicant + ".");
            }
        }
    }//GEN-LAST:event_btnLocateApplicantActionPerformed

    private void btnEvaluateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluateActionPerformed
        int years = Integer.parseInt((String) (cmbYears.getSelectedItem()));
        double interestRate = Double.parseDouble(txfInterest.getText());
        loanObj.setInterestRate(interestRate);
        loanObj.setYears(years);
        boolean appr = loanObj.isApproved();
        if (appr) {
            txaOutput.setText(loanObj.toString() + "\n\nLoan APPROVED with a monthly instalment of " + df.format(loanObj.calculateInstalment()));
            
        } else {
            txaOutput.setText("Name of applicant: " + loanObj.getApplicantName() + "\n");
            txaOutput.append("Loan NOT APPROVED");
        }
    }//GEN-LAST:event_btnEvaluateActionPerformed

    private void cmbApplicantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbApplicantsActionPerformed
        btnEvaluate.setEnabled(false);
        txaOutput.setText("");
    }//GEN-LAST:event_cmbApplicantsActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Question2_Memo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Question2_Memo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Question2_Memo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Question2_Memo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Question2_Memo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEvaluate;
    private javax.swing.JButton btnLocateApplicant;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbApplicants;
    private javax.swing.JComboBox cmbYears;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInterestRateH;
    private javax.swing.JLabel lblYearsH;
    private javax.swing.JPanel pnlApplicationStatus;
    private javax.swing.JPanel pnlPossibleApplicants;
    private javax.swing.JTextArea txaOutput;
    private javax.swing.JTextField txfInterest;
    // End of variables declaration//GEN-END:variables
}
