package Question1Package;

import java.awt.Color;
import java.awt.color.ColorSpace;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 * Possible solution for Question 1
 */
public class Question1_GUIMemo extends javax.swing.JFrame {

    String iD;

    public Question1_GUIMemo() {
        this.setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlButtons = new javax.swing.JPanel();
        btnQuest1_1 = new javax.swing.JButton();
        btnQuest1_2 = new javax.swing.JButton();
        btnQuest1_3 = new javax.swing.JButton();
        btnQuest1_4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnQuit = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txfFullNames = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txfID = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaNameTag = new javax.swing.JTextArea();
        txfSurname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaQ1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Question 1 -");

        pnlButtons.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnQuest1_1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnQuest1_1.setText("Question 1.1");
        btnQuest1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuest1_1ActionPerformed(evt);
            }
        });

        btnQuest1_2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnQuest1_2.setText("Question 1.2");
        btnQuest1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuest1_2ActionPerformed(evt);
            }
        });

        btnQuest1_3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnQuest1_3.setText("Question 1.3");
        btnQuest1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuest1_3ActionPerformed(evt);
            }
        });

        btnQuest1_4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnQuest1_4.setText("Question 1.4");
        btnQuest1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuest1_4ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Question1Package/logo.PNG"))); // NOI18N

        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonsLayout = new javax.swing.GroupLayout(pnlButtons);
        pnlButtons.setLayout(pnlButtonsLayout);
        pnlButtonsLayout.setHorizontalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlButtonsLayout.createSequentialGroup()
                        .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlButtonsLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlButtonsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnQuest1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlButtonsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnQuest1_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQuest1_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQuest1_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlButtonsLayout.setVerticalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQuest1_1)
                .addGap(33, 33, 33)
                .addComponent(btnQuest1_2)
                .addGap(32, 32, 32)
                .addComponent(btnQuest1_3)
                .addGap(32, 32, 32)
                .addComponent(btnQuest1_4)
                .addGap(35, 35, 35)
                .addComponent(btnQuit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblHeading.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(0, 51, 255));
        lblHeading.setText("Heading... <Q 1.1.>");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("First name:");

        txfFullNames.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txfFullNames.setText("Tandi Nkandla ");

        jLabel2.setText("Surname:");

        jLabel3.setText("ID:");

        txfID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txfID.setText("9904123456081");

        txaNameTag.setBackground(new java.awt.Color(227, 227, 227));
        txaNameTag.setColumns(20);
        txaNameTag.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txaNameTag.setRows(5);
        txaNameTag.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Name Tag", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 51, 255))); // NOI18N
        jScrollPane2.setViewportView(txaNameTag);

        txfSurname.setText("Mbali");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfFullNames)
                            .addComponent(txfID)
                            .addComponent(txfSurname))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfFullNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txaQ1.setBackground(new java.awt.Color(250, 250, 250));
        txaQ1.setColumns(20);
        txaQ1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        txaQ1.setRows(5);
        txaQ1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Purchases", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 51, 255))); // NOI18N
        jScrollPane1.setViewportView(txaQ1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHeading)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuest1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuest1_1ActionPerformed
        // Question 1.1. 
        lblHeading.setText("PC Athletics Championships");
    }//GEN-LAST:event_btnQuest1_1ActionPerformed

    private void btnQuest1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuest1_2ActionPerformed
        // Question 1.2
        String name = txfFullNames.getText();
        String surname = txfSurname.getText();
        iD = txfID.getText();
        String initials = "" + name.charAt(0);
        for (int i = 0; i < name.length(); i++) {
            if (name.charAt(i) == ' ') {
                initials += name.charAt(i + 1);
            }
        }

        int genderNum = Integer.parseInt(iD.substring(6, 10));
        String gender = "Female";
        if (genderNum >= 5000) {
            gender = "Male";
        }

        String tg = surname + " " + initials + ".";
        txaNameTag.setText("Athlete:\t" + tg.toUpperCase() + "\n\t" + gender);
    }//GEN-LAST:event_btnQuest1_2ActionPerformed

    private void btnQuest1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuest1_3ActionPerformed
        // Question 1.3
        String output = "\nAge group: ";
        int yrOfBirth = 0;

        int year = Integer.parseInt(txfID.getText().substring(0, 2));
        if (year <= 14) {
            yrOfBirth = 2000 + year;
        } else {
            yrOfBirth = 1900 + year;
        }
        int ageGr = 2014 - yrOfBirth;
        switch (ageGr) {
            case 14:
            case 15:
                output += "u/15";
                break;
            case 16:
            case 17:
                output += "u/17";
                break;
            case 18:
            case 19:
                output += "u/19";
                break;
            default:
                output += "Not eligible to participate";
        }
        txaNameTag.setText(txaNameTag.getText() + output);
    }//GEN-LAST:event_btnQuest1_3ActionPerformed

    private void btnQuest1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuest1_4ActionPerformed
        // Question 1.4
        DecimalFormat df = new DecimalFormat("R 0.00");
        String output;
        double price = Double.parseDouble(JOptionPane.showInputDialog("Please type unit price: "));
        int quantity = Integer.parseInt(JOptionPane.showInputDialog("Please type in the quantity: "));
        output = String.format("%-8s%-3s%-8s%-5s%-8s%-10s%-12s%n", "No", "", "Price", "", "Total", "Discount", "Amount Due");
        txaQ1.setText(output);
        double discount = 0;
        double totalDiscount = 0;
        for (int cnt = 1; cnt <= quantity; cnt++) {

            double cost = price * cnt;
            if (cnt % 2 == 0) {
                discount = price * cnt * 20 / 100;
            }

            output = String.format("%-8d%-3s%-8.2f%-5s%-8.2f%-10.2f%-10.2f%n", cnt, "X", price, "= R", (price * cnt), discount, ((price * cnt) - discount));
            txaQ1.append(output);
        }
        double amountTendered = Double.parseDouble(JOptionPane.showInputDialog("Enter the amount tendered"));
        double change = amountTendered - ((price * quantity) - discount);

        int rands, coins50, coins20, coins10;
        rands = (int) (change);
        double centsD = Math.round((change - rands) * 100);
        int cents = (int) (centsD);
        coins50 = cents / 50;
        cents %= 50;
        coins20 = cents / 20;
        cents %= 20;
        coins10 = cents / 10;
        cents %= 10;
        if(cents > 0)
        {
            coins10++;
        }
        

        txaQ1.append(String.format("%-15s%-10.2f%n", "Change:", change));
        if (rands > 0) {
            txaQ1.append(String.format("%-15s%-10s%n", "Rands:", rands));
        }
        if (coins50 > 0) {
            txaQ1.append(String.format("%-15s%-10s%n", "50c coins:", coins50));
        }
        if (coins20 > 0) {
            txaQ1.append(String.format("%-15s%-10s%n", "20c coins:", coins20));
        }
        if (coins10 > 0) {
            txaQ1.append(String.format("%-15s%-10s%n", "10c coins:", coins10));
        }
    }//GEN-LAST:event_btnQuest1_4ActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Question1_GUIMemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Question1_GUIMemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Question1_GUIMemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Question1_GUIMemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Question1_GUIMemo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuest1_1;
    private javax.swing.JButton btnQuest1_2;
    private javax.swing.JButton btnQuest1_3;
    private javax.swing.JButton btnQuest1_4;
    private javax.swing.JButton btnQuit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JTextArea txaNameTag;
    private javax.swing.JTextArea txaQ1;
    private javax.swing.JTextField txfFullNames;
    private javax.swing.JTextField txfID;
    private javax.swing.JTextField txfSurname;
    // End of variables declaration//GEN-END:variables
}
